export const SOURCES = ["Self", "Dealer", "Bank"];
export const STAGES = ["Lead", "Cibil", "Login", "Sanction", "Rejected", "Disbursed"];
export const PROFILE_TYPES = ["Sale Purchase", "Refinance", "Int Refinance", "BT", "Topup", "Int Topup"];
export const GENDERS = ["Male", "Female", "Other"];
export const CUSTOMER_PROFILES = ["Self-Employed", "Salaried", "ITR", "Agriculture"];
export const MARITAL_STATUSES = ["Un-married", "Married", "Married with Kids"];
export const DSAS = ["Wheels Web", "Girnar Software Pvt Ltd", "Kuwy", "Tractor Junction", "Cars Adda"];
export const MFG_YEARS = ["2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027"];
export const OS_NOS = ["1", "2", "3", "4", "5"];
export const RELATIONSHIPS = ["Father", "Mother", "Brother", "Spouse", "Son", "Daughter", "Sister"];
export const ADDRESS_PROOFS = ["As Per Aadhaar", "As Per Voter ID", "As Per Gas Bill", "As Per Agreements"];
export const ADDRESS_CATEGORIES = ["RENTED", "SELF-OWNED", "PARANTEL"];
export const BANKS = ["AXIS BANK", "Piramal", "Mahindra Finance", "Poonawalla Fincorp", "IDFC First Bank (Urban & Rural)", "HDFC Bank", "HDB FINANCE", "Bajaj Finserv", "ICICI Bank", "YES BANK LTD", "Tata Capital", "TVS Credit", "Muthoot Capital", "INDUSIND Bank", "EQUITAS SMALL FINANCE BANK", "Toyota Financial", "Manappuram Finance Limited", "AU FINANCE", "Cholamandalam Investment And Finance Company", "Saraswat Co-operative Bank", "Kotak Mahindra", "Bandhan Bank", "Kogta Financier", "Muthoot Money", "Fortune Finance", "Ambit Finvest Private Limited", "IKF Finance (White Board Cars)", "Mahaveer Finance", "Indostar Finance", "Vaasthu Finance", "Praveen Capital"];
export const DISBURSEMENT_STAGES = ["Filed", "Disbursed", "Cancellation"];
export const TENURES = Array.from({ length: 180 }, (_, i) => (i + 1).toString());
export const EMI_DATES = Array.from({ length: 31 }, (_, i) => (i + 1).toString());
export const RC_CARD_STATUSES = ["SELLER", "RTO", "WHEELS WEB", "CUSTOMER"];
